### ISSUE TITLE
[FEATURE] Improved categories

### ISSUE THREAD

**Issue by TheShark27** [aricneto/TwistyTimer#100]
It would be nice to be able to have longer names for categories, and also to be able to rename them without writing a new name, but modifying the existing one.

**Comment by dvd2000** [comment]
You can rename the category name by clicking on the category button, then on 'RENAME' and then you can select the category you want to rename.

**Comment by dvd2000** [comment]
Probably the 'Enter category name dialog' should have a 'CANCEL' button like the one on the 'Enter new name' dialog (the renaming dialog). The 'CANCEL' is also present on the 'Edit comment' dialog.

**Comment by TheShark27** [comment]
I know that it's already possible to rename a category, but it would be easier to be able to modify the existing name, instead of renaming with a completely new one, like we are able to do now. Just a little improvement :)

**Comment by dvd2000** [comment]
Ah, ok. You are suggesting to have an edit feature like the one for the comments. It is a good idea as it will make the app UI more consistent.

**Comment by TheShark27** [comment]
Yeah, exactly.
