### ISSUE TITLE
Megaminx scramble wrong?

### ISSUE THREAD

**Issue by jtarnoff** [aricneto/TwistyTimer#102]
When scrambling the megaminx, my colors end up on the wrong faces. I am attempting to scramble with white on U face and green on the F face. I know I'm following the scrambling instructions correctly because my pieces match the preview on all faces, but the colors are switched. I looked through source code on TNoodle and it looks like their default color scheme is white on U, green on F. Hopefully I'm just doing something wrong?

EDIT: it is probably worth noting that I also tried using TNoodle-WCA-0.11.5.jar and was able to successfully verify a couple of scrambles.

**Comment by royaruta** [comment]
Same issue with me, I can't verify correctly my scrambles on Megaminx. I think the problem is on the Scramble image display generation.

**Comment by aricneto** [comment]
With d4993979709f574ca97d6f739c0266605d47d8e8, the TNoodle lib has been updated to version 0.12.0, so this issue should be solved.
