### ISSUE TITLE
Diffetent averages between graph and text (Shifted Graph) [BUG] 

### ISSUE THREAD

**Issue by Combinacijusx** [aricneto/TwistyTimer#104]
My averages on 3BLD shows sub2 with text on bottom and above 2 on the graph. Maybe I'm wrong but I'm pretty sure it's bug. 
    My guess is that on text or graph representation averages are counted including DNFs times therefore different averages. 

![screenshot_2017-09-22-22-01-27](https://user-images.githubusercontent.com/16375702/30760788-3e12df8a-9fe4-11e7-8deb-abe09982afc8.png)

**Comment by dvd2000** [comment]
I checked on my phone and my times on the graph for the 3x3x3 puzzle are about 5 seconds higher than the ones on the stats table below. My PB is 17.97 and on the graph it is a bit above 21 seconds. The same applies to every point on the graph.

For the 2x2x2 it seems that all the times are shifted by 1.2 more or less (my best Ao12 of 6.37 is displayed at ~7.5).

So, yes, it seems there is an issue on the graph.

**Comment by XuLx** [comment]
For me it happens to all events, not only to those with high DNFs.

**Comment by TheShark27** [comment]
Same here, in the graph my graph my times are higher. The line goes over 30, while my worst was 26. They seem to be three or four seconds higher.
