### ISSUE TITLE
[Question/feature] Why is there no option to unarchive solves?

### ISSUE THREAD

**Issue by josephroque** [aricneto/TwistyTimer#109]
If I were to accidentally archive my solves, or if I wanted to unarchive a number of solves so I could share a histogram of my recent solves, is there any reason I shouldn't be able to do that? Would it potentially mess up any calculations or otherwise?

I'm just curious! I'd be interested in the ability to do that, even if it meant hand picking every solve I wanted to unarchive.

**Comment by Combinacijusx** [comment]
You **can** unarchive any solves you want. But you must do it one by one.

1. Press on archived solve.
2. In bottom left corner press 3 dots.
3. Unarchive.

I can't guaranty but look like it works without calculation errors.

**Comment by josephroque** [comment]
Looks like you’re right! That’s enough for me to close this issue.
