### ISSUE TITLE
[DEV] Add instructions for working with crowdin

### ISSUE THREAD

**Issue by xaviershay** [aricneto/TwistyTimer#112]
Say I need to add a new string, or change an existing one. What is the preferred way to do this that works best with the translation workflow?

Recommend adding something to the README.

**Comment by aricneto** [comment]
Added that to the readme in 70e7c9468d1c81fd535e27dcc9e8813ad3b36eda.

Also, sorry for the tremendously long delay in updating this repo, I kinda had a lot going for me to be able to pay attention to this project. I'll try to keep a slow rhythm from now on, fit in at least a little time each week to keep it alive.

Thanks so much for your contributions, I'll be reviewing and implementing them in the coming days.
