### ISSUE TITLE
Typo in German version

### ISSUE THREAD

**Issue by dancing-jules** [aricneto/TwistyTimer#115]
Hello, I use Twisty Timer in German and when a new scramble is generated, it says "Scramble **wind** generiert..." instead of "Scramble **wird** generiert...".

**Comment by freundTech** [comment]
You can suggest translations on [crowdin](https://crowdin.com/project/twisty-timer).
This specific error is already fixed there and should get into the app once @aricneto updates the translation files and releases a new update.
