### ISSUE TITLE
Different color schemes for multiple puzzles

### ISSUE THREAD

**Issue by qbasob** [aricneto/TwistyTimer#116]
Is it possible to select different color schemes for differents puzzles? Or same puzzle but in other category? I have two 3x3x3 with different color schemes, and one 2x2x2 with color scheme different from those two. So I have three puzzles with different color schemes. Is it possible to set these colors inside of this app?

**Comment by SpawnAliX** [comment]
I'd like the same feature. Essentially because of the same color representation for all puzzle including Megaminx (12 faces against 6) and Pyraminx (4 against 6 for NxNxN puzzles).

**Comment by aricneto** [comment]
I plan on adding this in a future update. Closed in favor of #118
