### ISSUE TITLE
Triggering Twisty Timer from a Stackmat Pro like CS Timer

### ISSUE THREAD

**Issue by SpawnAliX** [aricneto/TwistyTimer#119]
Hi,
I'd like to have the ability to connect a Stackmat Pro G4 hardware timer on earphone plug jack of the smartphone/tablet and configure Twisty Timer to listen mic jack input as well as CS Timer on computer. I don't know how it's hard to program, but it could turn your app as a totally must-have for all speedcubers.
Thank you per advance.

**Comment by aricneto** [comment]
Duplicate: #70
