### ISSUE TITLE
Adding scramble of our choice

### ISSUE THREAD

**Issue by SpawnAliX** [aricneto/TwistyTimer#121]
Hi,
On the internet, we can find many famous scrambles (i.e. some WR scrambles). It could be cool if we can enter manually scramble of our choice and also, if we can retry it as many times as we want.
Thanks.

**Comment by tchesket** [comment]
I just wrote a review on the app store mentioning this. It's one of the main things I would like to see as well.

**Comment by LucasAlfare** [comment]
I'll try add this feature on a fork of this project!

**Comment by aricneto** [comment]
Added in da84009 !
