### ISSUE TITLE
Weird tutorial in training section behavior [BUG]

### ISSUE THREAD

**Issue by TheShark27** [aricneto/TwistyTimer#127]
Iin the Training section, when refreshing the scramble, sometimes the "get started" message appears, even though the categories have already been selected. I feel like that message as the same chance of the different permutations/OLLs of appearing. 

The expected behavior would be: if no OLL/PLL is selected, the message will appear; otherwise, if something is selected, the user won't need it.

Great work btw!

**Comment by aricneto** [comment]
Fixed in 0f69bc4
