### ISSUE TITLE
"Back cancels solve" option changes averages stats.

### ISSUE THREAD

**Issue by druidalek** [aricneto/TwistyTimer#129]
Using back button to cancel a solve should not alter any stats.

**Comment by aricneto** [comment]
Upon close inspection, this bit is probably the culprit. Commenting here so I remember

https://github.com/aricneto/TwistyTimer/blob/092a338068b31d5234c57cca0b8dcf9097408dad/app/src/main/java/com/aricneto/twistytimer/fragment/TimerFragment.java#L280-L291

**Comment by aricneto** [comment]
That was it. Thanks for reporting, fixed in 3157869bd17d8d81a7a4f30a80bc3004a8adc457
