### ISSUE TITLE
Menu overlaps personal best notification

### ISSUE THREAD

**Issue by bryankroesbeek** [aricneto/TwistyTimer#137]
When getting a new PB, the notification is overlapped by the menu.

<img src="https://i.imgur.com/QXoSEYS.jpg" width="350" />

**Comment by aricneto** [comment]
Thanks for the report.

**To replicate this issue:**
Disable scramble generation in the settings and get a new PB.

**Comment by aricneto** [comment]
Fixed in e1c2641833a0ff7bdffbcd053a1c8df935b16ad1
