### ISSUE TITLE
publish app

### ISSUE THREAD

**Issue by LXD312569496** [aricneto/TwistyTimer#153]
Can I change the code and  add or update some funtions，and then publish it in some android app store?

**Comment by aricneto** [comment]
Yes! The code is under the GPL license, which means you can change and
redistribute the code as you wish, as long as you also make the source code
of your changes available under the same license.

I only ask that you do not use the name or icon of the app (Twisty Timer),
and make it clear that it is a fork of the original. This is technically
not required under the license, but I ask this as a personal courtesy :).
Cheers!
