### ISSUE TITLE
Import feature still doesn't work

### ISSUE THREAD

**Issue by hedgeg0d** [aricneto/TwistyTimer#187]
I have just converted .txt from csTimer to suitable for Twisty Timer format with script. When tried to import it said
"successfully " imported 50 solves(i had exactly 50 solves in cs), but they did not appear. I use the latest apk from github for now(4.7.0). Android 10.

**Comment by aricneto** [comment]
Did you check the archive (hourglass icon)?

**Comment by hedgeg0d** [comment]
Oh, sorry. I did not expected that they will appear there. Sorry for stupid question. Solved now
