### ISSUE TITLE
Trend line

### ISSUE THREAD

**Issue by aricneto** [aricneto/TwistyTimer#22]

**Comment by damo** [comment]
I have (mostly) implemented graphing of the Ao5 and Ao12 for the session graph and Ao50 and Ao100 for the all-time graph. Still a few things to fix, but it can be previewed at https://github.com/damo/TwistyTimer/tree/session_stats

**Comment by damo** [comment]
I've added some screen shots to issue #37 to demonstrate what my work-in-progress on graphing the best times and some average times looks like.
