### ISSUE TITLE
Exiting app by pressing back button (BUG)

### ISSUE THREAD

**Issue by Combinacijusx** [aricneto/TwistyTimer#51]
*From references
*From other tabs (like graph). It would be nice if after pressing back button you will get back to main timer tab

And it would be nice if you needed double back button press to exit app. It could show dialog or pop up "press again to exit"

**Comment by damo** [comment]
I agree that it would be sensible to return to the timer tab on hitting "Back" from most places. Exiting the app from the algorithm references just seems wrong. The timer tab seems like the sensible entry and exit point.

However, I have never liked the "press-twice-to-exit" behaviour. It makes me feel like the app thinks I'm an idiot (it might be right, but it is very impolite to imply it). Three thumbs down from me.

**Comment by Avinash-Bhat** [comment]
> And it would be nice if you needed double back button press to exit app. It could show dialog or pop up "press again to exit"

This will be a big mistake.
But this can be done if the timer is running. even then, I would be recommending against this as the app should continue the timer on a foreground service and show a notification of the timer progress.
