### ISSUE TITLE
Verbal 8- and 12-second warnings during inspection time

### ISSUE THREAD

**Issue by keelnar** [aricneto/TwistyTimer#54]
In WCA competitions, the competitor does not see how much inspection time they have remaining, and instead only gets a verbal warning after 8 and 12 seconds have passed. I'd appreciate Twisty Timer also providing such verbal warnings, so as to more closely imitate the format of a competition, and so that I do not have to look away from the puzzle to see how much time is remaining.

**Comment by xaviershay** [comment]
Should be closed, based on the linked issues.
