### ISSUE TITLE
Example format for text import correct

### ISSUE THREAD

**Issue by Nvidiot** [aricneto/TwistyTimer#68]
The example format shown in the dialog when importing a .txt format is incorrect. The pop-up shows: 

`"1:32.15"; "R U2"; "2016-03-16T08:16:42"`

But it should be:

`"4:24.58";"R U2";"2016-11-22T23:52:48.000+01:00" `

Importing a file just the first sample line leads to a crashing application. Importing the correct format works without a problem. I found the correct format by exporting some results and opening it with a text editor.

**Comment by aricneto** [comment]
This should be fixed once the next beta rolls out
