### ISSUE TITLE
Press back button twice to exit

### ISSUE THREAD

**Issue by dvd2000** [aricneto/TwistyTimer#74]
I find quite annoying that when I'm on the timer, times list or graph "page" if I press the back button the app will immediately close. I suggest that when I'm on the times list or on the graph, pressing the back button will take me to the timer "page", and pressing the button twice will close the app.

**Comment by aricneto** [comment]
This has been discussed in #51. I find pressing the back button twice to exit the app to be bad user design, but implementing the other behaviors should be OK.

**Comment by dvd2000** [comment]
Maybe the double press could be an option?

**Comment by aricneto** [comment]
Yeah, that could solve it.
