### ISSUE TITLE
Export to email

### ISSUE THREAD

**Issue by cbeust** [aricneto/TwistyTimer#76]
Love the app, really nicely done!

Would it be possible to export to email? Either a generic "Share to" intent or maybe just a specific one that will launch Gmail with the data as an attachment?

Thanks!

**Comment by dvd2000** [comment]
A "Share to" would be a nice feature to have, especially to share the times from your current session. For now it is possible to export your times to a text file and then you can send it as an attachment or share it in any other way.

**Comment by Combinacijusx** [comment]
@dvd2000 If I understood right what you want. You actually can share your time (even distribution). You need to go to current session times ( 2nd tab) and press plus button at the bottom right. There you can share and add times.

P.S I think that icon change to share button would be more intuitive.

**Comment by dvd2000** [comment]
@Combinacijusx Oh, I forgot that the Share feature was already there. For me, that's exactly what I wanted. I don't know if @cbeust was asking for something different. 

Yes, I think that the icon should be changed to something more intuitive like the usual "share button".

**Comment by aricneto** [comment]
Hey there!  
Thanks for the comment and suggestion. Sorry about the two-year delay haha, I've been quite busy with some other stuff. 

As of a1cf6d3650539f8f99afea4faa960282b0b457cd, you now have the option to share the backup file after export!
