### ISSUE TITLE
Incorrect scramble program for 4x4/5x5

### ISSUE THREAD

**Issue by KitClement** [aricneto/TwistyTimer#80]
Currently, the program uses BLD scrambles for 4x4 and 5x5, as they have rotations/wide turns at the end of the scrambles. 

Ideally, there would be an option to toggle random orientation on/off for 3x3-5x5 for those solving BLD so they could truly use official scrambles for those events while not having unnecessary wide turns/rotations when doing speedsolving events.

**Comment by aricneto** [comment]
4x4 and 5x5 now show correct scrambles in 845e8b2
