### ISSUE TITLE
Make app movable to SD card?

### ISSUE THREAD

**Issue by LunarGem** [aricneto/TwistyTimer#82]
Hello,

I've been cubing for a while, been coding for longer, and absolutely love this app. It's simple, no ads, and does everything I want/need it to do! I have just one problem: my phone is not top-of-the-line and only has 2GB of total memory (and half of that is Android bloatware). Could you possibly make this app movable to my (comparably enormous) SD card so I can try to conserve the little space that I have? I'm willing to help out if I can.

Thank you!

**Comment by aricneto** [comment]
845e8b2 - App can now move to SD card
