### ISSUE TITLE
How many solves before graph shows?

### ISSUE THREAD

**Issue by LunarGem** [aricneto/TwistyTimer#84]
Before I started using the app, the graph showed above the best table. Once my solves were in, though, the graph disappeared. I even uninstalled and reinstalled, and the graph showed, but when I imported my solves again, it disappeared. Do I need to have a certain number before the graph will show, or is there something else going on here?

Thanks!

**Comment by xsrvmy** [comment]
Your averages may be archived, in which case you need to press the hourglass button on the top. I am not getting this problem with less than 10 solves.
You could potentially have too many solves though.

**Comment by LunarGem** [comment]
I have a few Ao12s in there now and  it's still not displaying... Switching
to history doesn't show them. Is it possible my data is somehow corrupted?

**Comment by xsrvmy** [comment]
I don't know why that would be, because I am not the developer. You can check if the times display properly under the normal list of times.

**Comment by LunarGem** [comment]
I removed the solves and put some back in, the graph works now. I guess something must have been corrupted at some point.
