### ISSUE TITLE
Showing PB time scramble instead of new one. [FEATURE]

### ISSUE THREAD

**Issue by Combinacijusx** [aricneto/TwistyTimer#89]
When you get PB on screen there is text like you beat your personal best and stuff but there is new scramble instead of one you got PB on and this is problem when you want to do screenshot and show your friends. They might try scramble but it shows new one so you need to do other screenshot to show that scramble or even worse if they try that new scramble blah blah blah :D 
   And showing that scramble would be nice not only on PB times but on all times too.

   Solution: I think there could be some kind of button or stuff to switch between that and new scramble. Or just showing both scrambles tho it would look nice I think.  Or maybe some screenshot mode where you can share your time. Something like that.

**Comment by aricneto** [comment]
Showing two scrambles would be too confusing, I think the best way to solve this would be to make the button-switch thing, or to display PBs in the solve list dialogs.

**Comment by edgardmessias** [comment]
I'm trying to make a solution, see https://github.com/edgardmessias/TwistyTimer/tree/issue_89

After end, tap to generate a new sequence.

**Comment by aricneto** [comment]
It is a cool feature, but much too confusing for the user.

**Comment by edgardmessias** [comment]
My idea: after END, show a tooltip/button like "Touch to generate new scramble"
