### ISSUE TITLE
Wrong timer behavior when changing theme or color scheme

### ISSUE THREAD

**Issue by dvd2000** [aricneto/TwistyTimer#95]
To reproduce the issue:
1. Start the timer, (solve your cube), stop the timer
2. Open the side drawer
3. Click on App theme and change the colour

The last time won't be displayed anymore and the scramble will change.
The last time change isn't a big issue while the scramble change can be considered a bug ( Consider this situation: I scramble my cube following the displayed scramble then I decide to change the app theme before solving the cube. Now I have a different scramble and if I start the timer the solve will be saved with the wrong scramble).

The same thing will happen if you change the cube color scheme.

**Comment by aricneto** [comment]
Is this for 2.x? Since 3.0.0b1, with 5241ed5 (persistent scrambles on rotation), this should no longer be a problem.

**Comment by dvd2000** [comment]
Yes, sorry. That's for 2.x.
I'll close the issue

**Comment by dvd2000** [comment]
There is still a small problem:

When you change the app theme the timer screen refreshes (and for some milliseconds there is a black screen) so you have the impression that the scramble has been regenerated.

**Comment by dvd2000** [comment]
But that's really a little thing and I can imagine it would be quite difficult to fix (when you change the app theme the screen must redraw itself to update its colour. Maybe there is some possibility of time optimization?
