### ISSUE TITLE
BUG: Cross hints only shown for D

### ISSUE THREAD

**Issue by TheShark27** [aricneto/TwistyTimer#96]
1. Open the app
2. Tap on Hints
Only cross/extended cross hints for D will be shown.

**Comment by dvd2000** [comment]
Are you running the 3.0.0b1 release?

**Comment by TheShark27** [comment]
Yes, the new beta. I was about to comment that, sorry.

**Comment by dvd2000** [comment]
With the 3.0.0b1 version there is the possibility to choose the face for which the cross hint should be displayed. By default only the D face cross hint will show. There should be an option to select for which faces you want the hint.
I didn't test the beta yet but that's what I read from the release notes and from the commits ([this] is the commit that implemented this feature).

**Comment by TheShark27** [comment]
Oh, sorry. You're right, you can choose one or more colors to start the cross with. What a cool feature! Closing issue. Thank you very much!

**Comment by aricneto** [comment]
Yes, this is expected behavior in 3.0.0b1, you can now choose which sides you want the cross hints to show. Since it has caused some user confusion, I'll add a notice to the hints panel pointing it out for users that haven't yet changed the settings.

**Comment by TheShark27** [comment]
Great, thank you! A "temporary" one? (That disappear after the first time you've opened the hints)

**Comment by dvd2000** [comment]
The default for the hints is the D face but the default D face is the yellow one (on the color scheme). Usually non-color-neutral cubers solve the cross on the white face, so maybe using the U face as the default one could be better?

**Comment by dvd2000** [comment]
Also, why don't leave all the faces hints as default?

**Comment by TheShark27** [comment]
I think using U as default would be better. Maybe he decided to show cross hints for only one face to avoid long loading times.

**Comment by aricneto** [comment]
Yeah, I think I'll just leave them all as default. Initially I left only one as default since I thought it would make hints load faster, but it hasn't changed load time at all, the bottleneck is the indexing of each scramble.

**Comment by dvd2000** [comment]
> The default for the hints is the D face but the default D face is the yellow one (on the color scheme). Usually non-color-neutral cubers solve the cross on the white face, so maybe using the U face as the default one could be better?

Sorry, I've updated to the beta just now. I just saw that you choose the shown hints by selecting the colors on the color scheme. In this case I would say white should be the default one.

**Comment by TheShark27** [comment]
Well, if it may change the loading time it could be useful! But yeah, I've seen it hasn't changed much.

**Comment by dvd2000** [comment]
To me the hints loading time seems much shorter than before. Even with all the faces selected it loads in less time than before.

**Comment by TheShark27** [comment]
I've noticed that it takes some time to load the first hint, then if you change the scramble and tap hints it takes no time to load. Also if you solve instead of changing scramble.

**Comment by aricneto** [comment]
> To me the hints loading time seems much shorter than before. Even with all the faces selected it loads in less time than before.

I did do some things to slightly improve loading times, like limiting the number of solutions to a maximum of 3, and fixing a bug where previous hints would not cancel loading if you generated a new scramble. However, I didn't see any noticeable change to load times. I'm glad it worked for some people then!

> I've noticed that it takes some time to load the first hint, then if you change the scramble and tap hints it takes no time to load. Also if you solve instead of changing scramble.

Yes, that's what stumps me. The hint algorithm is not mine, it's taken from Prisma Puzzle Timer. It seems to spend most of the time generating the scramble index. Once it's generated the index for the first scramble, following scrambles will load almost instantly. I'm still studying it to see if I can improve it somehow.
