### ISSUE TITLE
Laggy behaviour

### ISSUE THREAD

**Issue by TheShark27** [aricneto/TwistyTimer#98]
I don't know what happened, but after switching to Square-1 the app became laggy, very noticeable when starting the inspection (the animation is laggy).
I don't know if it's something related to my phone or not.

**Comment by TheShark27** [comment]
I'm experiencing this on the new beta

**Comment by TheShark27** [comment]
( 3.0.0b1)

**Comment by TheShark27** [comment]
Ok, tested on another device (2015 Galaxy Tab A). Starting the inspection/the solve on the beta causes animation lag, while the stable version was very fluid. Square-1 isn't a problem, it always happens with any puzzle.

**Comment by TheShark27** [comment]
So, I'll summarize: starting an inspection or a solve causes the top bar to disappear, but in 3.0.0b1 that animation is laggy. Tested on Moto G⁴ Play and Galaxy Tab A (2015), both running Android 6.0.1

**Comment by dvd2000** [comment]
On my Sony Xperia Z3 Compact (Android 6.01) it is still very fluid

**Comment by TheShark27** [comment]
The App itself is fluid, but I'm experiencing lag with the starting timer animation and on the graph page. On the graph page because I have 636 solves (on the other device I have 0 and the graph page is fluid)

**Comment by dvd2000** [comment]
I have more than 2000 solves in 3x3x3 and 2x2x2 and I don't experience any lag in the graph page

**Comment by TheShark27** [comment]
Ok, I'll try to export later on the tablet and I'll let you know.

**Comment by TheShark27** [comment]
The graph doesn't lag at all, it's very fluid. Switching tabs animation from/to the graph page is laggy, and also opening the left bar.
